# Generated by Django 4.1.6 on 2023-02-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("loyalty_level", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["date_joined"],
            },
        ),
        migrations.CreateModel(
            name="WashingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["type"],
            },
        ),
        migrations.CreateModel(
            name="WashingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("washing_steps", models.ManyToManyField(to="wash.washingstep")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("price_after_discount", models.FloatField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wash.user"
                    ),
                ),
                (
                    "washing_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wash.washingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
